apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-node-cycle-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-node-cycle-operator
  template:
    metadata:
      labels:
        app: kube-node-cycle-operator
    spec:
      serviceAccountName: kube-node-cycler
      containers:
      - name: kube-node-cycle-operator
        image: quay.io/utilitywarehouse/kube-node-cycle-operator:0.1.3
        args:
        - operator
        - -state_path=/data/state.json
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: node-cycle-operator-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: node-cycle-operator-data
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pd-standard
  resources:
    requests:
      storage: 32Mi
